services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["rails", "server", "-b", "0.0.0.0"]
        entrypoint: /app/entrypoints/entrypoint.sh
        env_file:
            - .env.development
        environment:
            - DATABASE_HOST=database
            - WEBPACKER_DEV_SERVER_HOST=webpacker
        volumes: 
            - .:/app
            - gem_cache:/usr/local/bundle/gems
            - node_modules:/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - database
            - redis
            - webpacker
    webpacker:
        build: .
        environment:
            - NODE_ENV=development
            - RAILS_ENV=development
            - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
        command: ./bin/webpack-dev-server
        volumes:
            - .:/app
        ports:
            - "3035:3035"
    database:
        image: postgres
        env_file:
            - .env.development
        volumes:      
            - db_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379"
        volumes:
            - redis:/data

volumes:
    gem_cache:
    db_data:
    node_modules:
    redis:






