default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: webmenue_2021_development
  username: webmenue_db_user
  password: webmenue_2021

test:
  <<: *default
  database: webmenue_2021_test
  host: localhost
  username: webmenue_db_user
  password: webmenue_2021

production:
  <<: *default
  database: webmenue_2021_production
  username: webmenue_2021
  password: <%= ENV['WEBMENUE_2021_DATABASE_PASSWORD'] %>
