development:
  host: ldap.forumsys.com
  port: 389
  base: dc=example, dc=com
  username: cn=admin, dc=example, dc=com
  password: password

test:
  host: 127.0.0.1
  base: dc=test,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: secret

production:
  host: 127.0.0.1
  method: :tls
  base: dc=production,dc=local,dc=net
  bind_dn: cn=admin,dc=local,dc=net
  password: secret

